# 시계열 분석

## 시계열 분석: 현시점까지의 데이터로 앞으로 어떤 패턴의 차트를 스릴지 예측하는 분석기법.

In [1]:
file_path = '../documentum/data/market-price.csv'
bitcoin_df = pd.read_csv(file_path, names = ['day', 'price'])
bitcoin_df

NameError: name 'pd' is not defined

시계열 분석(time series analysis)이란,
독립변수 를 이용하여 종속변수를 예측하는 일반적인 기계학습 방법론에 대하여 시간을 독립변수로 사용한다는 특징이 있다. 독립변수로 시간을 사용하는 특성때문에 분석에 있어서 일반적인 방법론들과 다른 몇가지 고려가 필요하다

ARIMA(Autoregressive Intefreated Moving Average)
자기회기모형, 이동평균모형
ARIMA는 시계열의 비정상성을 설명하기 위해 관측지간의 차분을 사용한다.

- AR:자기회기: 이전 관측값의 오차항 이후 관측값에 영향을 주는 모형, theta는 자기상관계수, epsilond은 white noise 이다. Time lag 1이상이 될수 있다.
- I: Intgrated. 누적을 의미하는 것으로 차분을 이용하는 시계열모형들에 붙이는 표현
- MA : 이동평균. 관측값이 이전 연속전인 오차항의 영향을 받는다는 모형이다

In [24]:
import pandas as pd
test=pd.read_json('./data/market-price.json')

In [25]:
test

,status,name,unit,period,description,values
0,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1575763200, 'y': 7504.83}"
1,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1575849600, 'y': 7522.39}"
2,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1575936000, 'y': 7337.42}"
3,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1576022400, 'y': 7220.76}"
4,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1576108800, 'y': 7202.31}"
...,...,...,...,...,...,...
361,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1606953600, 'y': 19226.97}"
362,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1607040000, 'y': 19454.54}"
363,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1607126400, 'y': 18670.49}"
364,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1607212800, 'y': 19155.06}"
365,ok,Market Price (USD),USD,day,Average USD market price across major bitcoin ...,"{'x': 1607299200, 'y': 19377.66}"

In [34]:
test2= pd.read_csv('./data/market-price.csv', header=None , names=['Date', 'Price'])

In [35]:
test2

                    Date        Price
0    2017-08-27 00:00:00  4354.308333
1    2017-08-28 00:00:00  4391.673517
2    2017-08-29 00:00:00  4607.985450
3    2017-08-30 00:00:00  4594.987850
4    2017-08-31 00:00:00  4748.255000
..                   ...          ...
360  2018-08-22 00:00:00  6575.229167
361  2018-08-23 00:00:00  6434.881667
362  2018-08-24 00:00:00  6543.645714
363  2018-08-25 00:00:00  6719.429231
364  2018-08-26 00:00:00  6673.274167

[365 rows x 2 columns]